export enum ICON_RESPONSE_EVENTS {
  REQUEST_HAS_ACCOUNT,
  RESPONSE_HAS_ACCOUNT,
  REQUEST_HAS_ADDRESS,
  RESPONSE_HAS_ADDRESS,
  REQUEST_ADDRESS,
  RESPONSE_ADDRESS,
  'REQUEST_JSON-RPC',
  'RESPONSE_JSON-RPC',
  REQUEST_SIGNING,
}

export enum ICON_REQUEST_EVENTS {
  REQUEST_HAS_ACCOUNT,
  REQUEST_HAS_ADDRESS,
  REQUEST_ADDRESS,
  'REQUEST_JSON-RPC',
  REQUEST_SIGNING,
}
