import { ICON_REQUEST_EVENTS, ICON_RESPONSE_EVENTS } from './types/IconWallet.types';

export const EVENT_RESPONSE: Record<ICON_REQUEST_EVENTS, ICON_RESPONSE_EVENTS> = {
  [ICON_REQUEST_EVENTS.REQUEST_HAS_ACCOUNT]: ICON_RESPONSE_EVENTS.RESPONSE_HAS_ACCOUNT,
  [ICON_REQUEST_EVENTS.REQUEST_HAS_ADDRESS]: ICON_RESPONSE_EVENTS.RESPONSE_HAS_ADDRESS,
  [ICON_REQUEST_EVENTS.REQUEST_ADDRESS]: ICON_RESPONSE_EVENTS.RESPONSE_ADDRESS,
  [ICON_REQUEST_EVENTS['REQUEST_JSON-RPC']]: ICON_RESPONSE_EVENTS['RESPONSE_JSON-RPC'],
  [ICON_REQUEST_EVENTS.REQUEST_SIGNING]: ICON_RESPONSE_EVENTS.RESPONSE_SIGNING,
};
